(() => {
'use strict';
const $=id=>document.getElementById(id),B=window.BC,{blocks,questions,labels}=B,KEY='business-clarity-checkup-v4';
const empty=()=>({version:4,businessName:'',industry:'',teamSize:'',businessAge:'',businessSummary:'',answers:{},step:0,focus:'',completedAt:null});let state=empty(),result=null,downloadUrl=null,storageOK=true;
try{const v=JSON.parse(localStorage.getItem(KEY));if(v?.version===4){for(const k of ['businessName','industry','teamSize','businessAge','businessSummary','focus'])if(typeof v[k]==='string')state[k]=v[k].slice(0,k==='businessSummary'?600:80);state.step=Number.isInteger(v.step)?Math.max(0,Math.min(blocks.length-1,v.step)):0;for(const q of questions)if(Number.isInteger(v.answers?.[q.id])&&q.options[v.answers[q.id]])state.answers[q.id]=v.answers[q.id];state.completedAt=typeof v.completedAt==='number'?v.completedAt:null;}}catch{storageOK=false;}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const completeProfile=()=>state.businessName.trim()&&B.industries[state.industry]&&B.teams[state.teamSize]&&B.ages[state.businessAge]&&state.businessSummary.trim();
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));storageOK=true;}catch{storageOK=false;}document.querySelectorAll('.storage-status').forEach(el=>el.textContent=storageOK?'Jawaban tersimpan di browser ini dan tidak dikirim ke pengajar. Hindari data pribadi pelanggan.':'Penyimpanan browser tidak tersedia. Tetap lanjutkan, lalu unduh PDF sebelum menutup halaman.');$('resume').hidden=!state.businessName;}
function show(id){document.querySelectorAll('.view').forEach(e=>e.classList.toggle('active',e.id===id));document.body.dataset.view=id;document.querySelector('.nav [data-start]').hidden=id!=='landing';window.scrollTo({top:0,behavior:'instant'});const h=$(id).querySelector('h1,h2');if(h){h.tabIndex=-1;h.focus({preventScroll:true});}}
for(const [id,data] of [['industry',B.industries],['teamSize',B.teams],['businessAge',B.ages]])$(id).innerHTML='<option value="" disabled selected>Pilih salah satu</option>'+Object.entries(data).map(([v,t])=>`<option value="${v}">${esc(t)}</option>`).join('');
const profileKeys=['businessName','industry','teamSize','businessAge','businessSummary'];
function profile(){profileKeys.forEach(k=>$(k).value=state[k]);show('profile');}
profileKeys.forEach(k=>$(k).addEventListener('input',()=>{state[k]=$(k).value;state.completedAt=null;save();}));
$('profileForm').onsubmit=e=>{e.preventDefault();profileKeys.forEach(k=>state[k]=$(k).value.trim());if(!completeProfile()){ $('profileForm').reportValidity();return;}save();renderBlock();};
document.querySelectorAll('[data-home]').forEach(el=>el.onclick=e=>{e.preventDefault();show('landing');});document.querySelectorAll('[data-start]').forEach(el=>el.onclick=()=>completeProfile()?renderBlock():profile());$('resume').onclick=()=>completeProfile()?renderBlock():profile();$('changeProfile').onclick=profile;
const iconPaths=['<circle cx="9" cy="8" r="3"/><path d="M3 21v-3a6 6 0 0 1 12 0v3M17 5a3 3 0 0 1 0 6m1 3a5 5 0 0 1 3 4v3"/>','<path d="m12 3 9 9-9 9-9-9 9-9Z"/><path d="m8 12 3 3 5-6"/>','<circle cx="5" cy="12" r="3"/><circle cx="19" cy="5" r="3"/><circle cx="19" cy="19" r="3"/><path d="m8 11 8-5m-8 7 8 5"/>','<path d="M21 11a8 8 0 0 1-8 8H7l-4 3V11a9 9 0 0 1 18 0Z"/><path d="M7 10h10m-10 4h6"/>','<rect x="3" y="5" width="18" height="14" rx="2"/><circle cx="12" cy="12" r="3"/><path d="M6 12h1m10 0h1"/>','<rect x="3" y="8" width="18" height="13" rx="2"/><path d="M8 8V3h8v5M3 13h18m-10 0v3h2v-3"/>','<rect x="3" y="3" width="6" height="6" rx="1"/><rect x="15" y="15" width="6" height="6" rx="1"/><path d="M9 6h9v9M6 9v9h9"/>','<path d="m8 7 4-4 4 4m-4-4v12M3 13v6h6m12-6v6h-6M6 19l6-7 6 7"/>','<path d="M5 3h14v18l-3-2-4 2-4-2-3 2V3Z"/><path d="M8 8h8m-8 4h8m-8 4h4"/>'];
$('aspectsList').innerHTML=blocks.map((b,i)=>`<article class="aspect"><svg class="icon" viewBox="0 0 24 24" aria-hidden="true">${iconPaths[i]}</svg><h3>${esc(b.name)}</h3><p>${esc(b.intro)}</p><small>${String(i+1).padStart(2,'0')} / ${esc(b.bmc)}</small></article>`).join('');
function progress(){const n=questions.filter(q=>Number.isInteger(state.answers[q.id])).length;$('countLabel').textContent=n+' / '+questions.length+' terjawab';$('bar').style.width=n/questions.length*100+'%';document.querySelector('.track').setAttribute('aria-valuenow',n);}
function renderBlock(){if(!completeProfile()){profile();return;}result=null;const b=blocks[state.step];show('quiz');$('sideBusiness').textContent=state.businessName;$('stepLabel').textContent='Area '+(state.step+1)+' dari '+blocks.length;progress();
$('blockNav').innerHTML=blocks.map((x,i)=>{const n=x.questions.filter(q=>Number.isInteger(state.answers[q.id])).length;return `<li><button class="block-tab ${i===state.step?'active':''}" ${i===state.step?'aria-current="step"':''} data-step="${i}"><span class="num">${n===4?'✓':String(i+1).padStart(2,'0')}</span>${esc(x.name)}<small>${n}/4</small></button></li>`;}).join('');$('blockNav').querySelectorAll('button').forEach(el=>el.onclick=()=>{state.step=Number(el.dataset.step);save();renderBlock();});
$('questionBody').innerHTML=`<div class="block-intro"><p class="eyebrow">${esc(b.bmc.toUpperCase())}</p><h2 id="blockTitle">${esc(b.name)}</h2><p>${esc(b.intro)} Pilih satu jawaban pada setiap pertanyaan.</p></div>`+b.questions.map((q,i)=>`<section class="question-card" id="card-${q.id}"><p class="question-number">PERTANYAAN ${i+1} DARI 4</p><h3 class="question-title" id="title-${q.id}">${esc(q.title)}</h3><p class="hint" id="hint-${q.id}">${esc(q.hint)}</p><fieldset class="options" aria-describedby="hint-${q.id}"><legend class="sr-only">${esc(q.title)}</legend>${q.options.map((o,j)=>`<label class="option"><input type="radio" name="${q.id}" value="${j}" ${state.answers[q.id]===j?'checked':''}><span>${esc(o.label)}</span></label>`).join('')}</fieldset></section>`).join('');
$('questionBody').querySelectorAll('input').forEach(el=>el.onchange=()=>{state.answers[el.name]=Number(el.value);state.completedAt=null;save();progress();$('quizError').textContent='';$('card-'+el.name).classList.remove('missing');const nav=$('blockNav').querySelector('.active small');if(nav)nav.textContent=b.questions.filter(q=>Number.isInteger(state.answers[q.id])).length+'/4';});$('quizError').textContent='';$('prev').textContent=state.step===0?'← Profil usaha':'← Area sebelumnya';$('next').textContent=state.step===blocks.length-1?'Periksa jawaban →':'Area berikutnya →';$('blockTitle').tabIndex=-1;$('blockTitle').focus({preventScroll:true});}
function missingMessage(q){$('quizError').textContent='Lengkapi pertanyaan yang ditandai. Pilih jawaban yang paling sesuai dengan keadaan usaha Anda.';const el=$('card-'+q.id);el.classList.add('missing');el.scrollIntoView({behavior:'smooth',block:'center'});el.querySelector('input').focus({preventScroll:true});}
$('prev').onclick=()=>{if(state.step===0)return profile();state.step--;save();renderBlock();};$('next').onclick=()=>{const missing=blocks[state.step].questions.find(q=>!Number.isInteger(state.answers[q.id]));if(missing)return missingMessage(missing);if(state.step===blocks.length-1)return renderReview();state.step++;save();renderBlock();};
function renderReview(){show('review');$('reviewList').innerHTML=`<div class="review-profile"><h3>${esc(state.businessName)}</h3><p>${esc(B.industries[state.industry])} · ${esc(B.teams[state.teamSize])} · ${esc(B.ages[state.businessAge])}</p><p>${esc(state.businessSummary)}</p><button class="text-btn" id="editProfile">Ubah profil usaha</button></div>`+blocks.map((b,i)=>`<section class="review-block"><h3>${i+1}. ${esc(b.name)}</h3>${b.questions.map(q=>`<div class="review-answer"><div><strong>${esc(q.title)}</strong><button class="text-btn" data-edit="${i}" data-question="${q.id}" aria-label="Ubah jawaban ${esc(q.title)}">Ubah</button></div><p>${esc(q.options[state.answers[q.id]]?.label||'Belum dijawab')}</p></div>`).join('')}</section>`).join('');$('editProfile').onclick=profile;$('reviewList').querySelectorAll('[data-edit]').forEach(el=>el.onclick=()=>{state.step=Number(el.dataset.edit);save();renderBlock();$('card-'+el.dataset.question).scrollIntoView({block:'center',behavior:'smooth'});});}
$('reviewBack').onclick=renderBlock;$('edit').onclick=renderReview;$('analyze').onclick=()=>{const b=blocks.findIndex(x=>x.questions.some(q=>!Number.isInteger(state.answers[q.id])));if(b>=0){state.step=b;renderBlock();return missingMessage(blocks[b].questions.find(q=>!Number.isInteger(state.answers[q.id])));}renderResults();};
const badge=f=>`<span class="badge ${f.status}">${esc(labels[f.status])}</span>`;
const action=f=>`<div class="action-grid"><div><b>LANGKAH PERTAMA</b><p>${esc(f.action)}</p></div><div><b>HASIL YANG PERLU DIBUAT</b><p>${esc(f.check)}</p></div></div>`;
function finding(f,i){return `<article class="finding"><span class="finding-number">${String(i+1).padStart(2,'0')}</span><div>${badge(f)}<h3>${esc(f.title)}</h3><p class="quote"><strong>Jawaban Anda:</strong> ${esc(f.label)}</p><p>${esc(f.meaning)}</p>${action(f)}</div></article>`;}
function areaAnalysis(a,i,details=false){return `<article class="finding"><span class="finding-number">${String(i+1).padStart(2,'0')}</span><div>${badge(a)}<p class="eyebrow">${esc(a.name)}</p><h3>${esc(a.title)}</h3><p class="analysis-meaning">${esc(a.meaning)}</p>${action(a.lead)}<p class="analysis-outcome"><strong>Cara mengecek hasilnya:</strong> ${esc(a.verify)}</p>${details?`<details class="evidence-list"><summary>Lihat jawaban yang menjadi dasar</summary>${a.findings.map(f=>`<p><strong>${esc(f.question)}</strong><br>${esc(f.label)}</p>`).join('')}</details>`:''}</div></article>`;}
function renderResults(){result=B.analyze(state.answers,state);if(!state.completedAt)state.completedAt=Date.now();if(!result.priorities.some(f=>f.qid===state.focus))state.focus=result.topAreas[0].id;save();show('results');$('resultIdentity').textContent=state.businessName+' · '+new Date(state.completedAt).toLocaleDateString('id-ID',{day:'numeric',month:'long',year:'numeric'});$('resultTitle').textContent=result.headline;$('resultSummary').textContent=result.narrative;
$('profileContext').innerHTML=`<div><p class="eyebrow">KONTEKS USAHA ANDA</p><h3>${esc(B.industries[state.industry])}</h3><p>${esc(B.teams[state.teamSize])}, termasuk owner · ${esc(B.ages[state.businessAge])}</p><p>${esc(state.businessSummary)}</p><small class="micro">Ringkasan dari Anda, tidak dianalisis otomatis.</small></div><div>${result.context.map(t=>`<p>${esc(t)}</p>`).join('')}</div>`;
$('metrics').innerHTML=['issue','watch','unknown','good'].map(k=>`<div class="metric"><strong>${result.counts[k]}</strong><span>${esc(labels[k])}</span><small>dari 9 area bisnis</small><p class="status-help">${esc(B.explanations[k])}</p></div>`).join('');$('metrics').hidden=result.preOperating;
$('priorityHeading').textContent=result.preOperating?'Siapkan tiga hal ini sebelum mulai.':result.counts.issue?'Masalah yang perlu ditangani lebih dahulu.':result.counts.watch?'Hal yang perlu diperjelas lebih dahulu.':result.counts.unknown?'Cari informasi sebelum memutuskan.':'Jaga cara kerja yang sudah berjalan.';
$('priorityList').innerHTML=result.topAreas.map((a,i)=>areaAnalysis(a,i)).join('');
$('connections').innerHTML=(result.connections.length?result.connections.map(c=>`<article class="connection"><h3>${esc(c.title)}</h3><p><strong>Dasar jawaban:</strong> ${c.basis.map(esc).join(' + ')}</p><p>${esc(c.meaning)}</p><p><strong>Periksa berikutnya:</strong> ${esc(c.action)}</p></article>`).join(''):'<p class="area-summary">Jawaban Anda belum cukup untuk menghubungkan masalah di beberapa area. Mulai dari satu kejadian nyata, lalu periksa bagian usaha mana saja yang terlibat.</p>')+result.inconsistencies.map(t=>`<p class="form-note"><strong>Periksa kembali jawaban:</strong> ${esc(t)}</p>`).join('');
$('resultMap').innerHTML=result.areas.map((a,i)=>`<a class="map-item" data-open="${a.id}" href="#detail-${a.id}"><small>${String(i+1).padStart(2,'0')} / ${esc(a.bmc)}</small><strong>${esc(a.name)}</strong>${badge(a)}<p class="map-meaning">${esc(a.title)}</p></a>`).join('');$('blockResults').innerHTML=result.areas.map((a,i)=>`<details class="block-detail" id="detail-${a.id}"><summary>${esc(a.name)} — ${esc(labels[a.status])}</summary>${areaAnalysis(a,i,true)}</details>`).join('');$('resultMap').querySelectorAll('a').forEach(el=>el.onclick=()=>{$('detail-'+el.dataset.open).open=true;});
$('focusSelect').innerHTML=result.priorities.map(f=>`<option value="${f.qid}" ${f.qid===state.focus?'selected':''}>${esc(f.block+' — '+f.title)}</option>`).join('');updateFocus();$('downloadStatus').textContent='Laporan berisi profil, peta BMC, analisis tiap area, dan tindak lanjut.';}
function updateFocus(){const f=result.focusOptions.find(x=>x.qid===state.focus);$('focusPlan').innerHTML=`<h3>${esc(f.title)}</h3><p><strong>Tindakan:</strong><br>${esc(f.action)}</p><p><strong>Hasil kerja:</strong><br>${esc(f.check)}</p><p><strong>Cara memeriksa:</strong><br>${esc(f.verify)}</p>`;$('workshopPersonal').textContent='Bawa laporan ini dan fokus “'+f.block+'” sebagai bahan latihan. Pelajari kaitannya dengan bagian lain dalam model bisnis.';}
$('focusSelect').onchange=e=>{state.focus=e.target.value;save();updateFocus();};
document.querySelectorAll('.download').forEach(btn=>btn.onclick=async()=>{if(!result)return;const status=$('downloadStatus');document.querySelectorAll('.download').forEach(b=>b.disabled=true);status.textContent='Menyiapkan laporan PDF…';try{if(!window.jspdf?.jsPDF)throw Error('Pembuat PDF belum termuat. Muat ulang halaman dan coba kembali.');const assets=await window.loadBCReportAssets();const doc=window.createBCReport(window.jspdf.jsPDF,state,result,assets);const blob=doc.output('blob');if(downloadUrl)URL.revokeObjectURL(downloadUrl);downloadUrl=URL.createObjectURL(blob);const name='Business-Clarity-'+(state.businessName.replace(/[^a-zA-Z0-9 _-]/g,'').slice(0,60)||'Laporan')+'.pdf';const a=document.createElement('a');a.href=downloadUrl;a.download=name;document.body.appendChild(a);a.click();a.remove();status.textContent='Laporan PDF berhasil dibuat. Jika unduhan tidak muncul, ';const fallback=document.createElement('a');fallback.href=downloadUrl;fallback.download=name;fallback.textContent='simpan melalui tautan ini';status.appendChild(fallback);}catch(e){status.textContent='PDF belum berhasil dibuat. '+e.message;}finally{document.querySelectorAll('.download').forEach(b=>b.disabled=false);status.scrollIntoView({behavior:'smooth',block:'center'});}});
$('restart').onclick=()=>{if(!confirm('Mulai check-up baru? Unduh laporan sebelumnya terlebih dahulu. Jawaban tersimpan akan diganti.'))return;state=empty();result=null;save();profile();};save();if(completeProfile())renderBlock();else profile();
})();
