/* BMC organizes the topics. The response rules below are original educational rules,
   not a validated health scale. Notes never affect the interpretation. */
(function(root){
const O=(status,label,title,meaning,action,check)=>({status,label,title,meaning,action,check});
const U=(subject,action,check)=>O('unknown','Belum tahu / belum ada informasi untuk menjawab.',subject+' belum dapat dinilai.','Informasi belum cukup. Ini bukan bukti bahwa bagian ini buruk.',action,check);
const G=(label,title,action,check)=>O('good',label,title,'Jawaban Anda menunjukkan praktik pendukung sudah tersedia. Mutu dan hasilnya tetap perlu diperiksa dari catatan nyata.',action,check);
const blocks=[
{id:'customers',name:'Pelanggan utama',bmc:'Customer Segments',intro:'Siapa yang membeli dan apa kebutuhan mereka?',example:'Pelanggan utama kami adalah kantor kecil di Jakarta Selatan yang memesan makan siang untuk 10–30 orang.',questions:[
{id:'customer',title:'Dari transaksi terakhir, siapa pelanggan yang paling sering membeli?',hint:'Yang ditanyakan adalah pembeli nyata, bukan semua orang yang mungkin tertarik.',options:[
G('Saya bisa menyebut kelompok pelanggan utamanya berdasarkan catatan transaksi.','Pelanggan utama sudah dapat dikenali.','Kelompokkan 10 transaksi terakhir menurut tipe pelanggan.','Daftar kelompok pelanggan dan jumlah transaksinya.'),
O('watch','Saya punya perkiraan, tetapi belum membandingkannya dengan transaksi.','Gambaran pelanggan masih berdasarkan perkiraan.','Penawaran bisa diarahkan ke kelompok yang belum tentu paling sering membeli.','Ambil 10 transaksi terakhir, lalu tandai tipe pembelinya.','Perbandingan kelompok yang Anda perkirakan dengan kelompok yang benar-benar membeli.'),
O('watch','Pembeli beragam; saya belum tahu kelompok mana yang perlu diutamakan.','Belum ada kelompok pelanggan yang diprioritaskan.','Pelanggan beragam bukan masalah dengan sendirinya. Namun, kebutuhan tiap kelompok bisa berbeda.','Kelompokkan pembeli menurut kebutuhan yang serupa, lalu bandingkan frekuensi pembeliannya.','Dua atau tiga kelompok pelanggan beserta kebutuhan masing-masing.'),
U('Pelanggan utama','Catat siapa pembeli pada 10 transaksi berikutnya, tanpa menyimpan data pribadi sensitif.','Daftar tipe pelanggan dari transaksi nyata.') ]},
{id:'need',title:'Bagaimana Anda mengetahui kebutuhan utama pelanggan?',hint:'Contoh kebutuhan: makan siang tiba tepat waktu, bukan sekadar “ingin katering”.',options:[
G('Pelanggan pernah menjelaskan kebutuhannya, dan jawabannya saya catat.','Ada keterangan pelanggan tentang kebutuhannya.','Baca kembali lima percakapan pelanggan dan cari kebutuhan yang berulang.','Ringkasan kebutuhan beserta contoh ucapan pelanggan.'),
O('watch','Saya sering mendengarnya, tetapi belum mencatat atau merangkumnya.','Informasi kebutuhan masih tersebar.','Hal penting yang didengar bisa terlupakan atau berbeda antara owner dan tim.','Ringkas kebutuhan dari lima percakapan terakhir dalam satu catatan.','Satu daftar kebutuhan yang bisa dibaca bersama oleh tim.'),
O('watch','Saya terutama mengandalkan dugaan sendiri.','Kebutuhan pelanggan belum diperiksa langsung.','Produk mungkin sesuai, tetapi alasannya belum didukung keterangan pembeli.','Tanyakan kepada tiga pembeli: masalah apa yang mereka ingin selesaikan saat membeli?','Tiga jawaban asli pembeli, terpisah dari dugaan Anda.'),
U('Kebutuhan pelanggan','Tanyakan alasan pembelian kepada tiga pelanggan terakhir.','Catatan singkat kebutuhan yang mereka sebutkan.') ]}]},
{id:'value',name:'Nilai yang ditawarkan',bmc:'Value Propositions',intro:'Mengapa pelanggan memilih Anda?',example:'Katering kami mengantar sebelum pukul 11.30, sehingga makan siang kantor tidak terlambat.',questions:[
{id:'reason',title:'Apa dasar Anda mengetahui alasan pelanggan memilih bisnis Anda?',hint:'Alasan bisa berupa harga, kualitas, kemudahan, kecepatan, atau hal lain yang disebut pembeli.',options:[
G('Beberapa pelanggan sudah menyebutkan alasannya secara langsung.','Alasan memilih sudah mendapat masukan pelanggan.','Kumpulkan lima alasan pembelian dan bandingkan dengan janji pada promosi Anda.','Daftar alasan membeli dan kesesuaiannya dengan promosi.'),
O('watch','Saya menduga mereka memilih karena kualitas atau pelayanan, tetapi belum bertanya.','Alasan memilih masih berupa dugaan.','Keunggulan yang Anda tonjolkan belum tentu alasan utama pembeli.','Tanyakan kepada tiga pembeli: mengapa memilih kami dibanding pilihan lain?','Tiga alasan pembelian dengan kata-kata pelanggan sendiri.'),
O('watch','Saya tahu mereka tertarik saat diskon, tetapi belum tahu alasan lainnya.','Alasan memilih di luar diskon belum diketahui.','Promosi mungkin menarik transaksi, tetapi belum menunjukkan apa yang dihargai selain potongan harga.','Tanyakan alasan membeli kepada pelanggan yang membeli tanpa diskon.','Alasan pembelian tanpa diskon; bila belum ada pembeli, catat keterbatasan itu.'),
U('Alasan memilih','Tanyakan alasan memilih kepada tiga pembeli terakhir.','Jawaban pembeli, bukan hanya daftar keunggulan menurut tim.') ]},
{id:'promise',title:'Apakah hasil yang diterima pelanggan sesuai dengan janji penjualan?',hint:'Contoh: waktu pengiriman, kelengkapan pesanan, mutu barang, atau hasil layanan.',options:[
G('Pada pesanan terakhir yang diperiksa, janji utama terpenuhi.','Pemenuhan janji sudah diperiksa.','Pertahankan pemeriksaan satu janji utama pada pesanan berikutnya.','Catatan janji dan hasil aktual pada lima pesanan.'),
O('watch','Biasanya terpenuhi, tetapi masih bergantung pada pengawasan langsung saya.','Pemenuhan janji masih bergantung pada owner.','Saat Anda tidak hadir, konsistensi belum dapat dipastikan.','Tuliskan satu kriteria hasil yang harus dicek sebelum pesanan diserahkan.','Checklist hasil yang dapat digunakan tanpa menunggu owner.'),
O('issue','Ada keluhan berulang karena hasil tidak sesuai dengan yang dijanjikan.','Ketidaksesuaian janji sudah dirasakan pelanggan.','Keluhan berulang menunjukkan ada kesenjangan antara janji dan hasil; sumbernya perlu ditelusuri.','Ambil tiga keluhan terbaru. Cocokkan janji penjualan dengan hasil yang diterima.','Daftar kesenjangan janji–hasil dan satu titik proses yang perlu diperiksa.'),
U('Kesesuaian janji','Bandingkan janji dan hasil aktual dari lima pesanan terakhir.','Lima catatan janji, hasil, dan keluhan bila ada.') ]}]},
{id:'channels',name:'Saluran penjualan',bmc:'Channels',intro:'Dari mana pelanggan datang dan bagaimana mereka membeli?',example:'Pelanggan menemukan kami di Instagram, bertanya melalui WhatsApp, lalu menerima konfirmasi pesanan.',questions:[
{id:'source',title:'Apakah Anda tahu dari mana pelanggan yang jadi membeli pertama kali mengenal bisnis ini?',hint:'Bedakan sumber pembeli dengan jumlah pengikut atau orang yang sekadar bertanya.',options:[
G('Sumber pelanggan dicatat dan bisa dihubungkan dengan pembelian.','Sumber pelanggan sudah dapat ditelusuri.','Bandingkan sumber pelanggan pada 10 transaksi terakhir.','Jumlah pembeli dari tiap sumber, bukan hanya jumlah pengunjung.'),
O('watch','Saya tahu saluran yang ramai, tetapi tidak tahu mana yang menghasilkan pembeli.','Keramaian belum terhubung dengan transaksi.','Saluran yang ramai belum tentu paling banyak menghasilkan pembelian.','Tanyakan sumber perkenalan pada 10 pembeli berikutnya.','Daftar transaksi beserta sumber pelanggan.'),
O('watch','Kami memakai beberapa saluran, tetapi tidak mencatat sumber pelanggan.','Kontribusi tiap saluran belum terlihat.','Keputusan melanjutkan promosi belum memiliki dasar transaksi per saluran.','Tambahkan satu kolom sumber pelanggan pada catatan pesanan.','Catatan sumber pelanggan yang terisi untuk transaksi baru.'),
U('Sumber pembeli','Mulai menanyakan “Pertama tahu kami dari mana?” pada pembeli.','Sepuluh transaksi dengan sumber perkenalannya.') ]},
{id:'order',title:'Ketika pelanggan ingin membeli, bagaimana proses pemesanannya?',hint:'Lihat percakapan atau transaksi terakhir: apakah cara memesan, harga, dan langkah pembayaran mudah dipahami?',options:[
G('Pelanggan bisa mengikuti langkah pemesanan tanpa penjelasan berulang.','Alur pembelian sudah dapat diikuti.','Periksa kembali satu pemesanan dari awal hingga selesai.','Alur pemesanan singkat yang sesuai dengan proses nyata.'),
O('watch','Pelanggan sering bertanya ulang tentang cara pesan, harga, atau pembayaran.','Informasi pemesanan belum cukup jelas.','Pertanyaan berulang dapat menambah pekerjaan dan memperlambat pembelian.','Kumpulkan tiga pertanyaan paling sering, lalu letakkan jawabannya sebelum pelanggan memesan.','Panduan pemesanan ringkas beserta harga dan cara pembayaran.'),
O('issue','Ada pelanggan yang batal atau pesanan terlewat karena prosesnya membingungkan.','Hambatan pemesanan sudah berdampak pada transaksi.','Pembatalan yang Anda laporkan perlu ditelusuri pada langkah tertentu, bukan langsung dianggap masalah promosi.','Periksa tiga kejadian terbaru: di langkah mana pelanggan berhenti atau pesanan terlewat?','Satu titik hambatan dan perubahan alur yang akan dicoba.'),
U('Kemudahan pemesanan','Minta satu orang mencoba alur pemesanan dan mencatat titik yang membingungkan.','Daftar kendala pada langkah pemesanan yang benar-benar dicoba.') ]}]},
{id:'relationships',name:'Hubungan pelanggan',bmc:'Customer Relationships',intro:'Bagaimana pertanyaan dan keluhan ditangani?',example:'Admin menjawab pertanyaan saat jam kerja. Keluhan dicatat dan ditindaklanjuti sampai pelanggan menerima penyelesaian.',questions:[
{id:'response',title:'Siapa yang memastikan pertanyaan pelanggan tidak terlewat?',hint:'Bisa owner sendiri atau anggota tim. Yang penting adalah tanggung jawab dan pengecekannya.',options:[
G('Ada penanggung jawab dan pengecekan pesan yang belum ditangani.','Tanggung jawab merespons sudah jelas.','Periksa daftar pesan yang masih menunggu jawaban.','Daftar pesan terbuka dan orang yang akan menanganinya.'),
O('watch','Siapa pun yang sempat menjawab; belum ada pengecekan pesan yang tertinggal.','Tanggung jawab respons belum konsisten.','Pesan bisa tidak terurus ketika semua orang mengira sudah ditangani orang lain.','Tentukan satu penanggung jawab untuk memeriksa pesan yang belum terjawab setiap hari kerja.','Nama penanggung jawab dan daftar pesan yang masih terbuka.'),
O('issue','Ada pertanyaan atau pesanan yang benar-benar terlewat.','Pesan pelanggan sudah ada yang terlewat.','Kejadian ini berpotensi menghambat layanan atau transaksi, tetapi besar dampaknya belum dihitung.','Tinjau pesan tujuh hari terakhir dan pisahkan yang belum dijawab atau belum ditindaklanjuti.','Daftar pesan terlewat, status tindak lanjut, dan penanggung jawabnya.'),
U('Penanganan pesan','Periksa satu kanal pesan utama dan tentukan siapa yang mengecek pesan terbuka.','Daftar pesan terbuka serta penanggung jawabnya.') ]},
{id:'complaint',title:'Apa yang terjadi setelah pelanggan menyampaikan keluhan?',hint:'Jika belum ada keluhan, pilih pilihan yang menyebut kondisi tersebut; jangan mengarang pengalaman.',options:[
G('Keluhan dicatat, ditangani, dan penyelesaiannya dikonfirmasi.','Penyelesaian keluhan sudah memiliki tindak lanjut.','Periksa satu keluhan yang selesai: apakah pelanggan menerima penyelesaiannya?','Catatan keluhan, tindakan, dan konfirmasi penyelesaian.'),
O('watch','Keluhan ditangani saat muncul, tetapi tidak dicatat sampai selesai.','Penyelesaian keluhan belum terlacak.','Tim sulit memastikan kasus sudah benar-benar selesai atau masalah yang sama kembali terjadi.','Catat setiap keluhan dalam daftar sederhana: masalah, penanggung jawab, status.','Daftar keluhan yang menunjukkan mana yang sudah dan belum selesai.'),
O('issue','Ada keluhan yang berulang atau belum selesai tanpa tindak lanjut jelas.','Ada keluhan yang perlu dituntaskan.','Keluhan terbuka membutuhkan penyelesaian; keluhan berulang juga perlu pemeriksaan proses.','Pilih keluhan terbuka paling mendesak dan tetapkan tindakan serta waktu konfirmasi.','Satu kasus dengan tindakan, penanggung jawab, dan tanggal tindak lanjut.'),
O('unknown','Belum pernah ada keluhan / belum punya catatan untuk menilai.','Penanganan keluhan belum dapat dinilai.','Tidak ada keluhan yang diketahui bukan bukti bahwa semua pelanggan puas.','Siapkan cara menerima keluhan dan tanyakan pengalaman kepada tiga pelanggan.','Saluran keluhan yang jelas dan tiga masukan pelanggan.') ]}]},
{id:'revenue',name:'Sumber pendapatan',bmc:'Revenue Streams',intro:'Apa yang menghasilkan uang dan kapan uang diterima?',example:'Paket katering Rp25.000 per porsi. Pelanggan kantor membayar setiap Jumat lewat transfer.',questions:[
{id:'sales',title:'Apakah Anda bisa melihat penjualan dan uang yang sudah benar-benar diterima?',hint:'Penjualan belum tentu sudah dibayar. Contoh: pesanan Rp2 juta, baru dibayar DP Rp1 juta.',options:[
G('Ada catatan penjualan, pembayaran masuk, dan tagihan yang belum dibayar.','Penjualan dan penerimaan uang sudah dibedakan.','Cocokkan lima transaksi terakhir dengan pembayaran yang masuk.','Daftar penjualan, uang diterima, dan sisa tagihan yang saling cocok.'),
O('watch','Saya mencatat penjualan, tetapi belum memisahkan yang lunas dan belum lunas.','Penjualan belum dibedakan dari uang yang diterima.','Angka penjualan belum dapat menunjukkan berapa uang yang tersedia dari transaksi tersebut.','Tambahkan status lunas, nilai yang diterima, dan sisa tagihan pada catatan penjualan.','Daftar tagihan terbuka dengan nominal dan jatuh tempo.'),
O('watch','Saya hanya melihat saldo rekening atau uang tunai yang ada.','Saldo menjadi satu-satunya gambaran penerimaan.','Saldo dapat bercampur dengan setoran modal atau pengeluaran; tidak cukup untuk membaca penjualan.','Pisahkan transaksi penjualan dari setoran modal dan perpindahan uang.','Catatan penerimaan penjualan yang dapat dicocokkan dengan transaksi.'),
U('Penerimaan penjualan','Mulai catat lima transaksi: nilai penjualan, uang diterima, dan sisa pembayaran.','Lima transaksi dengan status pembayaran yang jelas.') ]},
{id:'payment',title:'Apakah pembayaran pelanggan diterima sesuai waktu yang disepakati?',hint:'Pembayaran langsung, DP, dan tempo sama-sama boleh. Yang diperiksa adalah kesesuaian dengan kesepakatannya.',options:[
G('Pembayaran langsung atau bertempo diterima sesuai kesepakatan pada transaksi yang diperiksa.','Waktu penerimaan sesuai kesepakatan.','Lanjutkan pemeriksaan tanggal pembayaran terhadap tanggal yang disepakati.','Catatan transaksi dan tanggal penerimaan aktual.'),
O('watch','Waktu pembayaran sering dibicarakan belakangan dan belum jelas sejak awal.','Kesepakatan pembayaran belum jelas.','Ketidakjelasan waktu pembayaran menyulitkan penjadwalan penerimaan uang.','Cantumkan jumlah, tahap pembayaran, dan jatuh tempo sebelum pesanan disetujui.','Format konfirmasi pesanan dengan ketentuan pembayaran.'),
O('issue','Ada pembayaran yang melewati jatuh tempo.','Ada pembayaran pelanggan yang terlambat.','Keterlambatan menunda penerimaan uang. Dampaknya terhadap kewajiban bisnis masih perlu dibandingkan.','Buat daftar tagihan lewat jatuh tempo dan tentukan tanggal tindak lanjut untuk tiap tagihan.','Daftar piutang terlambat: nominal, jatuh tempo, dan rencana penagihan.'),
U('Ketepatan pembayaran','Bandingkan tanggal yang disepakati dengan tanggal pembayaran lima transaksi.','Daftar transaksi tepat waktu dan terlambat, tanpa menebak.') ]}]},
{id:'resources',name:'Sumber daya utama',bmc:'Key Resources',intro:'Apakah orang, alat, dan persediaan mendukung pekerjaan?',example:'Kami membutuhkan dua juru masak, dapur produksi, dan bahan baku harian untuk melayani 100 porsi.',questions:[
{id:'capacity',title:'Saat menerima pesanan, apakah Anda mengecek kemampuan untuk memenuhinya?',hint:'Periksa ketersediaan orang, waktu, alat, stok, atau bahan yang dibutuhkan.',options:[
G('Ketersediaan orang, waktu, dan bahan atau alat dicek sebelum menerima pesanan.','Penerimaan pesanan mempertimbangkan kapasitas.','Bandingkan kebutuhan dan ketersediaan pada satu pesanan berikutnya.','Catatan kapasitas yang dipakai untuk memutuskan penerimaan pesanan.'),
O('watch','Biasanya diperkirakan saja; pengecekan belum rutin.','Pemeriksaan kapasitas belum konsisten.','Pesanan dapat diterima sebelum kebutuhan sumber dayanya diketahui.','Buat daftar singkat orang, waktu, bahan, dan alat sebelum menerima pesanan berikutnya.','Checklist ketersediaan sumber daya sebelum menyanggupi pesanan.'),
O('issue','Pesanan pernah terlambat atau ditolak mendadak karena orang, alat, atau stok tidak siap.','Keterbatasan sumber daya sudah mengganggu pesanan.','Ada kendala kapasitas yang perlu ditentukan sumbernya; belum tentu perlu merekrut atau membeli alat.','Pilih tiga kejadian terakhir dan catat sumber daya yang kurang serta waktu kejadiannya.','Daftar kendala kapasitas dan satu cara mengatur ulang pesanan atau jadwal.'),
U('Kecukupan kapasitas','Cocokkan kebutuhan satu pesanan dengan orang, waktu, alat, dan stok yang tersedia.','Perbandingan kebutuhan dan ketersediaan sumber daya.') ]},
{id:'backup',title:'Jika satu orang atau alat utama tidak tersedia, apakah pekerjaan masih bisa berjalan?',hint:'Termasuk saat owner tidak bisa hadir. Untuk usaha sendiri, pikirkan cara menunda, mengalihkan, atau memberi tahu pelanggan.',options:[
G('Ada pengganti atau cara penanganan yang sudah pernah dicoba.','Ada cara menghadapi ketidakhadiran sumber daya utama.','Periksa kembali apakah pengganti atau cara penanganan masih bisa digunakan.','Rencana pengganti yang memiliki kontak atau langkah jelas.'),
O('watch','Ada rencana pengganti, tetapi belum pernah dicoba.','Rencana pengganti belum diuji.','Rencana mungkin membantu, tetapi kemampuan menjalankannya belum terlihat.','Coba satu tugas kecil melalui pengganti atau cara alternatif.','Hasil percobaan dan bagian yang masih perlu disiapkan.'),
O('issue','Pekerjaan pernah berhenti karena orang atau alat itu tidak tersedia.','Ketergantungan pada satu sumber daya sudah menghentikan pekerjaan.','Gangguan yang Anda laporkan menunjukkan perlunya cara melanjutkan atau mengatur ulang layanan.','Pilih tugas yang berhenti dan buat alternatif: pengganti, penyewaan, atau jadwal ulang yang disepakati.','Satu rencana penanganan gangguan yang realistis dan dapat dihubungi.'),
U('Kesiapan pengganti','Tentukan satu orang atau alat yang paling sulit digantikan, lalu tuliskan pilihan saat tidak tersedia.','Satu skenario gangguan dan pilihan penanganannya.') ]}]},
{id:'activities',name:'Aktivitas utama',bmc:'Key Activities',intro:'Apakah pekerjaan inti konsisten dan terkendali?',example:'Setiap pesanan dicatat, bahan disiapkan, makanan diperiksa, lalu pengiriman dikonfirmasi.',questions:[
{id:'standard',title:'Bagaimana tim mengetahui pekerjaan utama sudah selesai dengan benar?',hint:'Contoh standar: jumlah sesuai pesanan, barang lolos pemeriksaan, atau layanan selesai sesuai kesepakatan.',options:[
G('Ada langkah dan kriteria hasil yang jelas, serta digunakan saat bekerja.','Standar kerja sudah dipakai.','Amati satu pekerjaan dan cocokkan hasilnya dengan kriteria yang ada.','Bukti pemeriksaan hasil kerja terhadap standar.'),
O('watch','Standar hanya dijelaskan lisan atau harus ditanyakan kembali kepada saya.','Standar kerja masih bergantung pada penjelasan owner.','Hasil antarorang bisa berbeda jika kriteria benar belum dipahami sama.','Tuliskan checklist satu pekerjaan yang paling sering dilakukan, termasuk tanda selesai dengan benar.','Checklist kerja satu halaman yang dapat diikuti tanpa penjelasan tambahan.'),
O('watch','Sudah ada catatan atau SOP, tetapi belum digunakan secara konsisten.','Dokumen standar belum menjadi kebiasaan kerja.','Keberadaan SOP belum memastikan pelaksanaan. Hambatan pemakaian perlu diperiksa.','Amati satu pelaksanaan dan tanyakan langkah SOP mana yang sulit dipakai.','Satu revisi SOP atau cara pengecekan yang sesuai praktik kerja.'),
U('Standar pekerjaan','Pilih satu pekerjaan inti dan tuliskan urutan serta kriteria hasilnya.','Checklist sederhana dengan kriteria hasil yang bisa diamati.') ]},
{id:'rework',title:'Apakah kesalahan pekerjaan yang sama masih berulang?',hint:'Misalnya pesanan salah, pengerjaan ulang, data hilang, atau pengiriman terlambat karena proses internal.',options:[
G('Pada pekerjaan terakhir yang diperiksa, kesalahan yang sama tidak berulang.','Tidak ada pengulangan yang ditemukan pada pekerjaan yang diperiksa.','Pertahankan catatan kesalahan dan cek kembali setelah beberapa pekerjaan berikutnya.','Catatan kejadian yang memungkinkan pemeriksaan ulang, bukan ingatan saja.'),
O('watch','Kesalahan diperbaiki saat terjadi, tetapi belum dicatat polanya.','Perbaikan masih berfokus pada kejadian saat itu.','Tanpa catatan, pengulangan dan sumber gangguan sulit dibedakan.','Catat setiap kesalahan selama satu minggu: kejadian, langkah proses, dan penanganannya.','Daftar kesalahan yang bisa dibandingkan untuk menemukan pengulangan.'),
O('issue','Ya, kesalahan yang sama menyebabkan pekerjaan diulang atau terlambat.','Kesalahan berulang sudah menambah pekerjaan.','Perbaikan pada hasil akhir belum cukup mencegah kejadian berikutnya. Sumber pengulangan perlu diperiksa.','Telusuri satu jenis kesalahan berulang ke langkah proses sebelum kesalahan terjadi. Tambahkan satu titik pemeriksaan.','Satu perubahan proses dan catatan apakah kesalahan masih muncul.'),
U('Pengulangan kesalahan','Periksa lima pekerjaan terakhir dan tanyakan mana yang harus diulang atau diperbaiki.','Daftar pekerjaan normal dan pekerjaan yang memerlukan perbaikan.') ]}]},
{id:'partners',name:'Mitra utama',bmc:'Key Partnerships',intro:'Apakah pihak luar mendukung janji bisnis Anda?',example:'Pemasok sayur mengirim sebelum pukul 06.00. Untuk pengiriman pelanggan, kami memakai kurir yang disepakati.',questions:[
{id:'partner',title:'Apakah pemasok atau mitra utama memenuhi kesepakatannya?',hint:'Contoh mitra: pemasok, kurir, penyedia bahan, atau pihak luar yang membantu melayani pelanggan.',options:[
G('Pada pesanan yang diperiksa, mutu dan waktu sesuai kesepakatan.','Kinerja mitra sudah dibandingkan dengan kesepakatan.','Catat mutu dan waktu aktual pada pengiriman atau pekerjaan mitra berikutnya.','Perbandingan kesepakatan dan realisasi mitra.'),
O('watch','Kami belum menyepakati mutu atau waktu secara jelas.','Standar layanan mitra belum jelas.','Tanpa kesepakatan, sulit menentukan kapan hasil mitra perlu diperbaiki.','Sepakati satu standar penting dengan mitra: mutu, jumlah, atau waktu.','Kesepakatan tertulis sederhana yang dapat diperiksa.'),
O('issue','Keterlambatan atau masalah mutu mitra pernah mengganggu layanan pelanggan.','Gangguan dari mitra sudah berdampak pada layanan.','Perlu dibedakan antara gangguan sekali dan pola berulang sebelum mengganti mitra.','Catat tiga kejadian terakhir dan bicarakan kesenjangan terhadap kesepakatan dengan mitra.','Daftar gangguan mitra dan kesepakatan perbaikannya.'),
O('na','Tidak ada mitra luar yang kritis bagi layanan bisnis ini.','Ketergantungan mitra kritis tidak dilaporkan.','Bagian ini tidak dijadikan kelemahan. Periksa kembali jika model bisnis berubah.','Tinjau kebutuhan mitra ketika menambah produk atau layanan.','Catatan apakah ada ketergantungan pihak luar yang baru.'),
U('Kinerja mitra','Bandingkan satu hasil mitra dengan waktu dan mutu yang dibutuhkan bisnis.','Catatan kesepakatan dan hasil aktual mitra.') ]},
{id:'alternative',title:'Jika mitra utama tidak dapat membantu, apa yang Anda lakukan?',hint:'Tidak selalu harus punya dua pemasok. Alternatif juga bisa berupa perubahan jadwal atau layanan yang disepakati pelanggan.',options:[
G('Ada pilihan pengganti atau penanganan yang sudah pernah dicoba.','Ada alternatif ketika mitra terganggu.','Periksa ketersediaan dan syarat alternatif tersebut.','Kontak, waktu, dan konsekuensi biaya dari alternatif.'),
O('watch','Ada calon alternatif, tetapi kemampuan atau syaratnya belum diperiksa.','Alternatif mitra belum siap digunakan.','Daftar nama saja belum menunjukkan apakah layanan dapat dilanjutkan saat diperlukan.','Hubungi satu calon alternatif dan tanyakan kapasitas, waktu, serta syaratnya.','Satu alternatif dengan informasi ketersediaan yang jelas.'),
O('watch','Belum ada alternatif atau cara penanganan.','Penanganan gangguan mitra belum disiapkan.','Ketergantungan belum tentu bermasalah sekarang, tetapi pilihan saat terjadi gangguan masih terbatas.','Tentukan satu skenario gangguan dan pilih pengganti atau cara menjadwalkan ulang layanan.','Rencana penanganan untuk satu ketergantungan utama.'),
O('na','Tidak ada mitra luar yang kritis bagi layanan bisnis ini.','Alternatif mitra kritis belum relevan.','Tidak dihitung sebagai kekurangan karena Anda tidak melaporkan ketergantungan kritis.','Tinjau kembali jika pekerjaan penting mulai dialihkan ke pihak luar.','Catatan kebutuhan alternatif saat model kerja berubah.'),
U('Alternatif mitra','Daftar pihak luar yang bila berhenti dapat mengganggu pelanggan, lalu pilih satu untuk diperiksa.','Daftar ketergantungan nyata sebelum menentukan pengganti.') ]}]},
{id:'costs',name:'Struktur biaya',bmc:'Cost Structure',intro:'Apa biaya bisnis dan apakah transaksi menutup biayanya?',example:'Biaya kami meliputi bahan makanan, kemasan, pengiriman, gaji, dan sewa dapur. Pengeluaran pribadi dicatat terpisah.',questions:[
{id:'expense',title:'Bagaimana pengeluaran bisnis dicatat?',hint:'Termasuk pembelian bahan, gaji, sewa, dan pengeluaran bisnis lain; pengeluaran pribadi perlu dibedakan.',options:[
G('Pengeluaran bisnis dicatat dan dibedakan dari pengeluaran pribadi.','Pengeluaran bisnis sudah dapat ditelusuri.','Cocokkan catatan dengan bukti pengeluaran satu minggu terakhir.','Daftar pengeluaran bisnis yang cocok dengan bukti transaksi.'),
O('watch','Sebagian dicatat, tetapi masih ada pengeluaran yang terlewat.','Catatan biaya belum lengkap.','Biaya yang terlewat dapat membuat perkiraan hasil usaha tampak lebih baik dari kenyataannya.','Periksa bukti pembayaran tujuh hari terakhir dan masukkan biaya yang belum tercatat.','Catatan pengeluaran satu minggu dengan bukti pendukung.'),
O('watch','Uang bisnis dan pribadi masih bercampur tanpa pembeda di catatan.','Pengeluaran pribadi dan bisnis belum dibedakan.','Sulit melihat biaya operasi jika pengambilan pribadi tercampur sebagai pengeluaran usaha.','Tandai pengeluaran satu minggu sebagai biaya bisnis, pengambilan pribadi, atau hal yang perlu diperiksa.','Daftar biaya bisnis terpisah dari pengambilan pribadi.'),
U('Pengeluaran bisnis','Kumpulkan bukti pengeluaran tujuh hari terakhir dan catat jenis serta nilainya.','Daftar pengeluaran awal yang dapat dibandingkan dengan penerimaan.') ]},
{id:'margin',title:'Untuk satu produk atau layanan utama, apakah harga jual menutup biaya langsungnya?',hint:'Biaya langsung timbul untuk pesanan tersebut, misalnya bahan, kemasan, komisi, dan ongkir yang Anda tanggung. Sisa ini belum sama dengan laba bersih.',options:[
G('Sudah dihitung; harga jual melebihi biaya langsung pada transaksi yang diperiksa.','Transaksi yang diperiksa memiliki sisa setelah biaya langsung.','Periksa apakah sisa dari seluruh penjualan cukup untuk menutup biaya tetap bisnis.','Perhitungan terpisah: harga, biaya langsung, sisa, dan biaya tetap. Ini belum membuktikan laba bersih.'),
O('watch','Saya memperkirakan ada sisa, tetapi belum menghitung biaya langsung secara lengkap.','Sisa per transaksi masih berupa perkiraan.','Komponen kecil yang terlewat dapat mengubah sisa uang dari sebuah penjualan.','Hitung satu transaksi lengkap: harga yang diterima dikurangi semua biaya langsungnya.','Perhitungan sisa per transaksi dengan rincian biaya, sebelum biaya tetap.'),
O('issue','Pada transaksi yang diperiksa, harga jual tidak menutup biaya langsung.','Ada transaksi yang belum menutup biaya langsung.','Transaksi tersebut belum menghasilkan sisa untuk membantu menutup biaya tetap. Jangan menganggap semua produk sama tanpa pemeriksaan.','Periksa kembali biaya dan diskon pada transaksi itu; bandingkan dengan transaksi lain untuk produk yang sama.','Perbandingan harga dan biaya langsung sebelum memutuskan harga, biaya, atau promosi.'),
U('Sisa setelah biaya langsung','Pilih satu transaksi dan rinci harga, bahan, komisi, ongkir yang ditanggung, serta biaya langsung lainnya.','Perhitungan harga dikurangi biaya langsung; biaya tetap diperiksa terpisah.') ]}]}
];
const additional={
customers:[
{id:'segments',title:'Apakah kebutuhan kelompok pelanggan Anda berbeda?',hint:'Contoh: pelanggan perorangan membeli satuan, sedangkan kantor memerlukan jadwal dan jumlah tetap.',options:[
G('Ya, perbedaannya sudah dikenali dan pelayanan disesuaikan.','Perbedaan kebutuhan antarkelompok sudah diperhatikan.','Bandingkan cara melayani dua kelompok pelanggan utama.','Catatan kebutuhan dan cara pelayanan tiap kelompok.'),
O('watch','Ada beberapa kelompok, tetapi semuanya dilayani dengan cara yang sama tanpa diperiksa kebutuhannya.','Perbedaan kebutuhan belum diperiksa.','Satu cara pelayanan mungkin cukup, tetapi belum diketahui apakah cocok untuk semua kelompok.','Bandingkan kebutuhan tiga pembeli dari dua kelompok yang berbeda.','Daftar kebutuhan yang sama dan berbeda sebelum mengubah pelayanan.'),
G('Kami melayani satu kelompok dengan kebutuhan yang serupa dan sudah diperiksa.','Bisnis memiliki kelompok pelanggan yang terfokus.','Periksa apakah kebutuhan pembeli baru masih sesuai kelompok yang dilayani.','Catatan batas kelompok yang menjadi fokus.'),
U('Perbedaan kebutuhan pelanggan','Kelompokkan lima pembeli berdasarkan kebutuhan pembeliannya.','Dua atau tiga pola kebutuhan dari pembeli nyata.') ]},
{id:'customerPriority',title:'Apa dasar Anda memilih pelanggan yang paling ingin dilayani?',hint:'Pertimbangkan kecocokan kebutuhan, kemampuan melayani, dan pengalaman transaksi; tidak harus melayani semua orang.',options:[
G('Ada pilihan kelompok berdasarkan pengalaman transaksi dan kemampuan bisnis melayani.','Fokus pelanggan memiliki dasar pengalaman.','Bandingkan pilihan kelompok dengan transaksi dan sumber daya yang dipakai.','Alasan memilih kelompok pelanggan yang dapat ditunjukkan.'),
O('watch','Kami menerima semua pelanggan; belum pernah menentukan fokus.','Fokus pelanggan belum ditetapkan.','Menerima berbagai pelanggan boleh, tetapi prioritas layanan dan promosi menjadi sulit ditentukan bila kebutuhannya saling berbeda.','Pilih satu kelompok yang kebutuhannya paling sesuai dengan kemampuan bisnis saat ini.','Satu kelompok prioritas beserta alasan pemilihannya.'),
O('watch','Kami sudah memilih kelompok, tetapi terutama berdasarkan dugaan.','Pilihan kelompok belum didukung transaksi.','Fokus sudah ada, namun perlu diperiksa apakah kelompok tersebut benar-benar membutuhkan dan membeli penawaran.','Bandingkan dugaan dengan lima pembeli atau percakapan calon pembeli yang relevan.','Catatan dukungan atau perbedaan antara pilihan awal dan pengalaman nyata.'),
U('Fokus pelanggan','Tuliskan dua calon kelompok dan periksa kebutuhan serta kemampuan Anda melayaninya.','Perbandingan kelompok untuk menentukan fokus pemeriksaan.') ]}],
value:[
{id:'problem',title:'Apakah manfaat utama produk atau layanan sudah dijelaskan secara konkret?',hint:'Contoh: “makan siang kantor tiba sebelum 11.30”, bukan hanya “kualitas terbaik”.',options:[
G('Manfaat dijelaskan sebagai hasil yang jelas bagi pelanggan.','Manfaat penawaran sudah konkret.','Cocokkan manfaat yang ditulis dengan hasil yang dirasakan pelanggan.','Satu kalimat manfaat beserta bukti pengalaman pelanggan.'),
O('watch','Penjelasan masih umum, seperti berkualitas, terbaik, atau terpercaya.','Manfaat masih dijelaskan secara umum.','Pelanggan belum mendapat gambaran spesifik tentang hasil yang akan diperoleh.','Ubah satu klaim umum menjadi hasil yang bisa diamati pelanggan.','Satu kalimat manfaat yang menyebut hasil, bukan hanya kata sifat.'),
O('watch','Kami terutama menjelaskan fitur atau isi paket, belum manfaatnya.','Fitur belum dihubungkan dengan kebutuhan pelanggan.','Pembeli harus menyimpulkan sendiri mengapa fitur tersebut berguna.','Pilih satu fitur dan jelaskan kebutuhan pelanggan yang dibantunya.','Hubungan fitur, kebutuhan, dan manfaat dalam satu contoh.'),
U('Manfaat penawaran','Tanyakan kepada tiga pembeli hasil apa yang mereka harapkan dari pembelian.','Satu manfaat utama dengan dasar keterangan pembeli.') ]},
{id:'difference',title:'Apakah Anda tahu pilihan lain yang dipertimbangkan pelanggan sebelum membeli?',hint:'Alternatif bisa pesaing, mengerjakan sendiri, atau menunda pembelian.',options:[
G('Pelanggan pernah menyebut alternatifnya dan alasan memilih kami.','Pembeda dibanding alternatif memiliki masukan pembeli.','Bandingkan satu alternatif dengan alasan pelanggan memilih bisnis Anda.','Perbandingan penawaran berdasarkan hal yang dihargai pelanggan.'),
O('watch','Kami tahu pesaing, tetapi belum tahu perbandingan yang dibuat pelanggan.','Pembeda masih dilihat dari sisi bisnis.','Perbedaan produk belum tentu sama dengan perbedaan yang dianggap penting oleh pembeli.','Tanyakan kepada tiga pembeli pilihan lain yang mereka pertimbangkan.','Daftar alternatif dan alasan keputusan pembeli.'),
O('watch','Kami belum pernah memeriksa pilihan lain; biasanya hanya membandingkan harga.','Perbandingan penawaran masih terbatas pada harga.','Manfaat, kemudahan, atau waktu layanan mungkin juga menjadi pertimbangan yang belum diperiksa.','Bandingkan penawaran Anda dan satu alternatif pada harga, manfaat, serta cara layanan.','Tabel perbandingan sederhana yang kemudian dikonfirmasi ke pembeli.'),
U('Alternatif pelanggan','Tanyakan apa yang akan pelanggan lakukan jika tidak membeli dari bisnis Anda.','Tiga jawaban tentang alternatif yang nyata.') ]}],
channels:[
{id:'channelReview',title:'Bagaimana Anda memutuskan saluran promosi yang dilanjutkan?',hint:'Misalnya Instagram, marketplace, toko, reseller, atau rekomendasi pelanggan.',options:[
G('Saya membandingkan pembelian yang dihasilkan dengan biaya atau waktu yang digunakan.','Evaluasi saluran memakai hasil dan sumber daya.','Tinjau satu saluran menggunakan data transaksi dan biaya atau waktu pada periode yang sama.','Perbandingan saluran dengan periode pengamatan yang jelas.'),
O('watch','Saya terutama melihat jumlah tayangan, pengikut, atau pesan masuk.','Evaluasi saluran belum sampai ke pembelian.','Aktivitas audiens belum menunjukkan berapa transaksi yang terjadi.','Hubungkan sepuluh pertanyaan masuk dengan status jadi membeli atau tidak.','Catatan pertanyaan masuk dan pembelian per saluran.'),
O('watch','Saya menjalankan promosi seperti biasa tanpa evaluasi hasil.','Saluran belum ditinjau secara berkala.','Waktu dan biaya dapat terus dipakai tanpa mengetahui kontribusinya.','Pilih satu saluran dan catat kegiatan, biaya atau waktu, serta pembelian yang dapat ditelusuri.','Catatan evaluasi satu saluran sebelum menambah saluran baru.'),
U('Hasil saluran promosi','Catat asal lima pembeli berikutnya dan kegiatan promosi terkait bila diketahui.','Catatan awal untuk membandingkan hasil saluran.') ]},
{id:'delivery',title:'Apakah produk atau layanan sampai ke pelanggan sesuai kesepakatan?',hint:'Termasuk barang diterima lengkap, layanan selesai, atau akses kelas berhasil diberikan.',options:[
G('Penyerahan diperiksa dan pelanggan menerima sesuai kesepakatan.','Penyerahan kepada pelanggan sudah diperiksa.','Pertahankan konfirmasi penerimaan untuk pesanan berikutnya.','Catatan penyerahan dan konfirmasi penerimaan pelanggan.'),
O('watch','Biasanya sampai, tetapi belum ada pengecekan atau konfirmasi penerimaan.','Tahap penyerahan belum terpantau.','Bisnis belum bisa memastikan kapan tanggung jawab penyerahan benar-benar selesai.','Tambahkan konfirmasi penerimaan pada satu jenis pesanan.','Status setiap pesanan: diproses, diserahkan, dan diterima.'),
O('issue','Ada keterlambatan, barang kurang, atau akses layanan gagal diterima.','Ada gangguan pada penyerahan kepada pelanggan.','Gangguan terjadi setelah pembelian; titik penyerahan perlu ditelusuri sebelum menambah promosi.','Periksa tiga kejadian terakhir dan tentukan tahap penyerahan yang gagal.','Daftar gangguan penyerahan dengan langkah penanganannya.'),
U('Penyerahan kepada pelanggan','Periksa status penerimaan lima pesanan atau layanan terakhir.','Catatan mana yang sudah diterima sesuai kesepakatan.') ]}],
relationships:[
{id:'followup',title:'Apakah pengalaman pelanggan diperiksa setelah pembelian selesai?',hint:'Contoh: memastikan barang dapat digunakan atau hasil layanan sesuai kebutuhan.',options:[
G('Ada tindak lanjut yang sesuai jenis produk atau layanan.','Pengalaman setelah pembelian diperhatikan.','Tinjau tiga hasil tindak lanjut dan catat masukan yang berulang.','Ringkasan masukan setelah pembelian.'),
O('watch','Kadang dilakukan, tergantung waktu luang.','Tindak lanjut belum menjadi kebiasaan.','Masukan dari pembeli yang tidak mengeluh dapat terlewat.','Pilih satu titik tindak lanjut yang sesuai siklus produk atau layanan.','Waktu dan pertanyaan tindak lanjut yang sederhana.'),
O('watch','Kami menunggu pelanggan menghubungi bila ada masalah.','Pengalaman setelah pembelian belum ditanyakan.','Tidak adanya pesan masuk belum menjelaskan pengalaman pelanggan.','Hubungi tiga pembeli terakhir untuk menanyakan pengalaman penggunaan.','Tiga masukan pelanggan yang dapat ditindaklanjuti.'),
U('Pengalaman setelah pembelian','Pilih tiga pembeli yang produknya sudah digunakan atau layanannya sudah selesai.','Catatan pengalaman mereka setelah transaksi.') ]},
{id:'retention',title:'Bagaimana Anda mengetahui pelanggan kembali membeli atau merekomendasikan bisnis?',hint:'Untuk produk yang jarang dibeli ulang, rekomendasi atau rujukan pelanggan lebih relevan.',options:[
G('Pembelian ulang atau rekomendasi dicatat sesuai karakter bisnis.','Hubungan lanjutan dengan pelanggan dapat ditelusuri.','Periksa sumber pembelian ulang atau rekomendasi pada transaksi terakhir.','Catatan transaksi dari pelanggan lama atau rujukan.'),
O('watch','Saya mengenali beberapa pelanggan lama, tetapi tidak mencatatnya.','Hubungan lanjutan masih bergantung pada ingatan.','Sulit membedakan hasil tindak lanjut dari kebetulan bila tidak ada catatan.','Tandai transaksi pelanggan lama atau pembeli yang datang dari rekomendasi.','Catatan sederhana asal hubungan pelanggan.'),
O('issue','Pelanggan yang sebelumnya rutin membeli berhenti, dan penyebabnya belum diperiksa.','Ada pelanggan rutin yang berhenti membeli.','Perubahan ini perlu ditelusuri; belum tentu disebabkan kualitas atau harga.','Tanyakan pengalaman dan perubahan kebutuhan kepada beberapa pelanggan yang berhenti.','Catatan alasan dari pelanggan sebelum memilih tindakan mempertahankan mereka.'),
U('Pembelian ulang atau rekomendasi','Tanyakan pada pembeli baru apakah datang dari rekomendasi; tandai pembeli yang kembali.','Catatan awal pembelian ulang atau rujukan yang sesuai bisnis.') ]}],
revenue:[
{id:'incomeModel',title:'Apakah Anda tahu produk atau layanan mana yang menghasilkan pendapatan utama?',hint:'Misalnya jual satuan, paket proyek, langganan, komisi, atau sewa.',options:[
G('Pendapatan dipisahkan menurut produk, layanan, atau cara penjualannya.','Sumber pendapatan utama dapat ditelusuri.','Bandingkan penerimaan dari masing-masing produk atau layanan pada satu periode.','Daftar sumber pendapatan dan kontribusinya.'),
O('watch','Saya tahu totalnya, tetapi belum memisahkan menurut produk atau layanan.','Kontribusi sumber pendapatan belum terlihat.','Produk yang terlihat ramai belum tentu paling banyak menyumbang penerimaan.','Kelompokkan penjualan satu periode menurut produk atau layanan.','Daftar penjualan per sumber pendapatan.'),
O('watch','Saya punya dugaan produk utama, tetapi belum ada catatannya.','Sumber pendapatan utama masih perkiraan.','Keputusan fokus produk belum didukung perbandingan transaksi.','Kelompokkan sepuluh transaksi terakhir menurut produk atau layanan.','Perbandingan transaksi untuk memeriksa dugaan produk utama.'),
U('Sumber pendapatan','Tuliskan apa yang dibayar pelanggan dan bagaimana cara pembayarannya.','Daftar sumber pendapatan yang akan diperiksa melalui transaksi.') ]},
{id:'pricing',title:'Apa dasar harga yang Anda tawarkan kepada pelanggan?',hint:'Tidak harus rumit: biaya, nilai manfaat, pilihan lain, dan respons pembeli perlu dipertimbangkan.',options:[
G('Harga mempertimbangkan biaya dan sudah dibandingkan dengan respons pembeli atau alternatif pasar.','Harga memiliki dasar yang bisa diperiksa.','Tinjau satu harga dengan biaya aktual dan respons pembeli terakhir.','Catatan dasar harga beserta hal yang perlu diperbarui.'),
O('watch','Terutama mengikuti harga pesaing, belum menghitung biaya sendiri.','Harga pasar belum dicocokkan dengan biaya sendiri.','Biaya bisnis Anda bisa berbeda dari pesaing, sehingga harga serupa belum tentu memberi hasil yang sama.','Hitung biaya langsung untuk satu produk sebelum menilai kesesuaian harganya.','Perbandingan harga jual dan biaya langsung sendiri.'),
O('watch','Harga atau diskon sering diputuskan saat negosiasi tanpa batas yang jelas.','Penetapan harga saat negosiasi belum memiliki batas.','Konsistensi penawaran dan hasil transaksi sulit dijaga jika diskon berubah tanpa dasar.','Catat harga serta potongan pada lima transaksi dan periksa biaya langsung masing-masing.','Dasar batas diskon yang ditinjau dari hasil transaksi, bukan tebakan.'),
U('Dasar harga','Pilih satu produk, tuliskan biaya yang diketahui dan harga yang diterima pelanggan.','Catatan komponen harga yang sudah diketahui dan perlu diperiksa.') ]}],
resources:[
{id:'resourceList',title:'Apakah kebutuhan utama untuk menjalankan pekerjaan sudah diketahui?',hint:'Orang, keterampilan, alat, bahan, tempat, akses aplikasi, atau modal kerja yang dibutuhkan.',options:[
G('Kebutuhan utama diketahui dan diperiksa ketersediaannya.','Kebutuhan sumber daya sudah dipetakan.','Periksa satu pekerjaan dan cocokkan sumber daya yang benar-benar digunakan.','Daftar kebutuhan sumber daya yang sesuai pekerjaan nyata.'),
O('watch','Kebutuhannya dipahami owner, tetapi belum dicatat.','Informasi sumber daya masih tersimpan di kepala owner.','Persiapan sulit ditinjau atau diteruskan ketika owner tidak tersedia.','Catat kebutuhan satu pekerjaan berulang berikut jumlah atau akses yang diperlukan.','Daftar kebutuhan kerja yang bisa diperiksa ulang.'),
O('issue','Pekerjaan sering dimulai lalu berhenti karena kebutuhan penting baru diketahui.','Kebutuhan yang terlewat sudah menghentikan pekerjaan.','Persiapan belum menangkap semua kebutuhan penting; membeli tambahan belum tentu menyelesaikan sumber masalah.','Telusuri satu pekerjaan yang berhenti dan tambahkan kebutuhan yang terlewat ke pemeriksaan awal.','Checklist kesiapan sebelum pekerjaan dimulai.'),
U('Kebutuhan sumber daya','Ikuti satu pekerjaan dari awal sampai selesai dan catat sumber daya yang dipakai.','Daftar awal sumber daya penting.') ]},
{id:'information',title:'Apakah informasi penting bisnis mudah ditemukan saat diperlukan?',hint:'Misalnya catatan pesanan, harga terbaru, kontak pemasok, file kerja, dan akses aplikasi.',options:[
G('Informasi tersimpan teratur dan dapat diakses oleh orang yang berwenang.','Informasi penting dapat ditemukan dan diakses.','Coba menemukan satu dokumen yang dibutuhkan untuk pekerjaan hari ini.','Lokasi dokumen, versi yang benar, dan hak akses yang jelas.'),
O('watch','Informasi tersebar di chat, perangkat, atau ingatan owner.','Informasi penting masih tersebar.','Mencari informasi dapat menambah waktu dan risiko memakai versi yang keliru.','Pusatkan lima dokumen yang paling sering diperlukan dalam satu folder dengan nama yang jelas.','Daftar dokumen utama dan lokasi penyimpanannya.'),
O('issue','Pekerjaan pernah terhambat karena file, catatan, atau akses tidak ditemukan.','Akses informasi sudah menghambat pekerjaan.','Gangguan tersebut perlu ditangani melalui penyimpanan dan akses, bukan hanya mengingatkan orang.','Pulihkan satu informasi yang hilang, tentukan penyimpanan utama, dan periksa cadangannya.','Satu sumber informasi yang dapat diakses dan dipulihkan.'),
U('Ketersediaan informasi','Daftar lima informasi yang paling sering dicari saat bekerja.','Daftar informasi beserta lokasi dan pemegang aksesnya.') ]}],
activities:[
{id:'workflow',title:'Apakah alur pekerjaan dari pesanan masuk sampai selesai sudah jelas?',hint:'Periksa urutan langkah, siapa yang mengerjakan, dan kapan pekerjaan diteruskan.',options:[
G('Urutan dan tanggung jawab jelas serta dipakai saat bekerja.','Alur pekerjaan sudah dapat diikuti.','Cocokkan alur tertulis atau yang disepakati dengan satu pesanan terbaru.','Alur kerja yang sesuai praktik dan menunjukkan penanggung jawabnya.'),
O('watch','Alurnya dipahami dari kebiasaan, tetapi sering perlu bertanya kembali.','Alur kerja masih bergantung pada ingatan.','Pergantian orang atau peningkatan pesanan dapat membuat langkah penting terlewat.','Tuliskan urutan satu jenis pesanan, dari penerimaan sampai penyerahan.','Alur sederhana yang menunjukkan perpindahan pekerjaan.'),
O('issue','Pekerjaan pernah terlewat atau dikerjakan dua kali karena alur tidak jelas.','Ketidakjelasan alur sudah mengganggu pelaksanaan.','Perlu diperiksa di titik mana tugas diterima atau diteruskan, bukan langsung menyalahkan orang.','Telusuri satu kejadian dan tetapkan siapa yang menyerahkan serta menerima tugas pada titik itu.','Satu perbaikan serah-terima pekerjaan dengan tanda selesai.'),
U('Alur pekerjaan','Amati satu pesanan dan catat langkah yang benar-benar dilalui.','Peta alur kerja awal dari pengalaman nyata.') ]},
{id:'quality',title:'Kapan hasil pekerjaan diperiksa sebelum diterima pelanggan?',hint:'Contoh: pemeriksaan jumlah, ukuran, isi dokumen, atau fungsi produk.',options:[
G('Ada pemeriksaan sebelum diserahkan, dengan kriteria yang jelas.','Pemeriksaan hasil dilakukan sebelum penyerahan.','Tinjau satu hasil yang lolos pemeriksaan dan pastikan kriterianya masih relevan.','Bukti pemeriksaan terhadap kriteria hasil.'),
O('watch','Kadang diperiksa, tetapi bergantung pada siapa yang sempat.','Pemeriksaan hasil belum konsisten.','Kesalahan mungkin baru diketahui setelah pelanggan menerima hasilnya.','Pilih tiga hal yang wajib dicek sebelum satu jenis pesanan diserahkan.','Checklist pemeriksaan akhir yang singkat.'),
O('issue','Kesalahan biasanya baru diketahui setelah pelanggan mengeluh.','Pelanggan menjadi pihak pertama yang menemukan kesalahan.','Kesalahan sudah melewati proses internal dan perlu dicegah sebelum penyerahan.','Ambil satu kesalahan dari keluhan dan tambahkan pemeriksaan sebelum hasil diserahkan.','Titik pemeriksaan baru dan catatan pelaksanaannya.'),
U('Pemeriksaan hasil','Periksa siapa atau apa yang memastikan satu pesanan layak diserahkan.','Tiga kriteria dasar hasil yang dapat diamati.') ]}],
partners:[
{id:'dependency',title:'Apakah Anda tahu pihak luar mana yang paling menentukan kelancaran bisnis?',hint:'Misalnya pemasok bahan, kurir, platform, tenaga spesialis, atau penyedia fasilitas.',options:[
G('Pihak luar yang kritis sudah dikenali beserta dampak jika terganggu.','Ketergantungan pada pihak luar sudah dikenali.','Tinjau satu mitra kritis dan bagian layanan yang bergantung padanya.','Daftar ketergantungan dan dampak gangguan pada pekerjaan.'),
O('watch','Kami tahu siapa mitranya, tetapi belum menilai mana yang paling kritis.','Tingkat ketergantungan mitra belum dipetakan.','Gangguan kecil dan gangguan yang menghentikan layanan belum dibedakan.','Urutkan mitra berdasarkan apakah pekerjaan tetap bisa berjalan saat mereka tidak tersedia.','Daftar mitra kritis untuk diperiksa lebih dahulu.'),
O('na','Bisnis tidak memiliki ketergantungan pihak luar yang kritis saat ini.','Tidak ada ketergantungan mitra kritis yang dilaporkan.','Kondisi ini tidak dianggap kelemahan.','Tinjau kembali saat mengalihkan pekerjaan ke pihak luar.','Catatan ketergantungan baru bila model kerja berubah.'),
U('Ketergantungan mitra','Tuliskan pihak luar yang membantu melayani pelanggan dan apa perannya.','Daftar pihak luar beserta pekerjaannya.') ]},
{id:'agreement',title:'Apakah ruang lingkup kerja dan biaya mitra disepakati sebelum pekerjaan dimulai?',hint:'Kesepakatan sederhana melalui pesan tertulis dapat menjadi catatan awal tentang pekerjaan, biaya, dan perubahan.',options:[
G('Pekerjaan, biaya, dan cara menangani perubahan disepakati serta dicatat.','Kesepakatan kerja mitra sudah tercatat.','Periksa satu pekerjaan mitra terhadap ruang lingkup dan biaya yang disetujui.','Catatan kesepakatan dan perubahan yang dapat ditelusuri.'),
O('watch','Sebagian disepakati lisan; detail atau perubahan belum selalu dicatat.','Kesepakatan mitra belum lengkap.','Perbedaan ingatan tentang pekerjaan atau biaya dapat menyulitkan penyelesaian.','Ringkas ruang lingkup, biaya, dan perubahan melalui konfirmasi tertulis.','Satu catatan kesepakatan yang dipahami kedua pihak.'),
O('issue','Pernah terjadi salah paham pekerjaan atau biaya tambahan yang tidak disepakati.','Ketidakjelasan kesepakatan sudah menimbulkan gangguan.','Kejadian perlu ditelusuri ke bagian yang belum disepakati sebelum pekerjaan berikutnya dimulai.','Catat perbedaan kesepakatan pada satu kejadian dan konfirmasikan batas pekerjaan berikutnya.','Ruang lingkup dan biaya yang dikonfirmasi sebelum mulai.'),
O('na','Tidak ada mitra luar yang kritis bagi layanan bisnis ini.','Kesepakatan mitra kritis belum relevan.','Tidak dihitung sebagai kelemahan.','Tentukan kesepakatan saat mulai menggunakan mitra kritis.','Catatan kebutuhan mitra jika model kerja berubah.'),
U('Kesepakatan mitra','Periksa satu pesanan atau pekerjaan mitra: apa yang disepakati dan berapa biayanya?','Catatan ruang lingkup dan biaya yang sudah diketahui.') ]}],
costs:[
{id:'fixedCost',title:'Apakah Anda bisa membedakan biaya rutin dan biaya yang mengikuti jumlah penjualan?',hint:'Contoh: sewa tetap dibayar saat sepi, sedangkan bahan dan kemasan mengikuti jumlah pesanan.',options:[
G('Biaya rutin dan biaya yang mengikuti penjualan dipisahkan dalam catatan.','Perilaku biaya sudah dibedakan.','Periksa apakah pemisahan tersebut sesuai pengeluaran aktual satu periode.','Daftar biaya tetap dan biaya yang berubah mengikuti penjualan.'),
O('watch','Semua biaya dicatat menjadi satu, belum dibedakan.','Biaya belum dikelompokkan menurut perilakunya.','Sulit memperkirakan biaya ketika penjualan naik atau turun.','Kelompokkan pengeluaran satu bulan menjadi biaya rutin dan biaya mengikuti transaksi.','Dua kelompok biaya dengan rincian komponen utamanya.'),
O('watch','Saya terutama menghitung bahan atau modal barang; biaya rutin belum lengkap.','Biaya rutin belum masuk dalam gambaran usaha.','Sisa setelah bahan atau barang belum menunjukkan kemampuan menutup seluruh pengeluaran bisnis.','Tambahkan sewa, gaji tetap, langganan, dan biaya rutin lain ke daftar pengeluaran.','Daftar biaya rutin di luar biaya langsung transaksi.'),
U('Kelompok biaya','Daftar pengeluaran yang tetap terjadi meskipun tidak ada penjualan.','Daftar awal biaya rutin untuk dibandingkan dengan biaya per pesanan.') ]},
{id:'budget',title:'Apakah pengeluaran aktual dibandingkan dengan rencana atau batas yang Anda tetapkan?',hint:'Mulai dari pengeluaran utama; tidak harus memakai sistem anggaran yang rumit.',options:[
G('Ada batas atau rencana, dan selisihnya diperiksa secara berkala.','Pengeluaran aktual sudah ditinjau terhadap rencana.','Periksa satu selisih pengeluaran dan catat alasan perubahannya.','Perbandingan rencana dan aktual beserta penjelasannya.'),
O('watch','Ada perkiraan pengeluaran, tetapi belum dibandingkan dengan kenyataannya.','Rencana pengeluaran belum dievaluasi.','Perkiraan belum membantu pengendalian bila selisihnya tidak diperiksa.','Bandingkan tiga pengeluaran utama dengan perkiraan awal.','Daftar selisih biaya dan alasan yang diketahui.'),
O('issue','Pengeluaran pernah melebihi rencana sampai pembayaran kebutuhan lain tertunda.','Kelebihan pengeluaran sudah mengganggu pembayaran lain.','Perlu dibedakan antara perubahan biaya, jadwal pembayaran, dan penerimaan yang terlambat.','Bandingkan pengeluaran yang melampaui rencana dengan kewajiban yang tertunda.','Daftar selisih biaya dan jadwal pembayaran yang perlu ditata.'),
U('Pengendalian pengeluaran','Tetapkan perkiraan tiga pengeluaran utama untuk periode berikutnya, lalu catat realisasinya.','Catatan rencana dan aktual pengeluaran utama.') ]}]
};
blocks.forEach(b=>b.questions.push(...additional[b.id]));
const labels={issue:'Kendala dilaporkan',watch:'Belum konsisten',unknown:'Belum diketahui',good:'Praktik tersedia',na:'Tidak relevan saat ini'};
const industries={food:'Makanan & minuman',retail:'Retail & perdagangan',manufacturing:'Produksi & manufaktur',service:'Jasa profesional & agency',education:'Pendidikan & pelatihan',property:'Properti & konstruksi',health:'Kesehatan & kebugaran',beauty:'Kecantikan & perawatan',travel:'Penginapan & pariwisata',logistics:'Transportasi & logistik',agriculture:'Pertanian & peternakan',digital:'Teknologi & produk digital',other:'Lainnya'};
const teams={solo:'Sendiri',small:'2–5 orang',medium:'6–10 orang',growing:'11–25 orang',large:'26–50 orang',larger:'Lebih dari 50 orang'};
const ages={pre:'Belum beroperasi',new:'Kurang dari 1 tahun',early:'1–3 tahun',established:'Lebih dari 3–5 tahun',mature:'Lebih dari 5 tahun'};
const WA='https://api.whatsapp.com/send/?phone=62851213142611&text&type=phone_number&app_absent=0';
const questions=blocks.flatMap(b=>b.questions.map(q=>({...q,block:b})));
function analyze(answers,profile={}){
const findings=questions.map(q=>{const v=answers[q.id];if(!Number.isInteger(v)||!q.options[v])throw Error('Jawaban belum lengkap: '+q.id);return {...q.options[v],qid:q.id,question:q.title,blockId:q.block.id,block:q.block.name,bmc:q.block.bmc};});
const counts=Object.fromEntries(Object.keys(labels).map(s=>[s,findings.filter(f=>f.status===s).length]));
const order={issue:0,watch:1,unknown:2,good:3,na:4};
const priorities=[...findings].filter(f=>f.status!=='na').sort((a,b)=>order[a.status]-order[b.status]);
const areas=blocks.map(b=>{const fs=findings.filter(f=>f.blockId===b.id);return {...b,findings:fs,status:[...fs].sort((a,b)=>order[a.status]-order[b.status])[0].status};});
const by=id=>findings.find(f=>f.qid===id);const connections=[];
if(by('promise').status==='issue'&&by('rework').status==='issue')connections.push({title:'Janji pelanggan dan proses kerja perlu diperiksa bersama.',basis:[by('promise').label,by('rework').label],meaning:'Keluhan tentang janji dan kesalahan berulang sama-sama dilaporkan. Keduanya mungkin berkaitan, tetapi jawaban ini belum membuktikan penyebabnya.',action:'Cocokkan satu keluhan dengan catatan pekerjaan pada pesanan yang sama. Temukan apakah kesalahan proses itu benar-benar terkait.'});
if(by('payment').status==='issue'&&by('expense').status!=='good')connections.push({title:'Pembayaran terlambat perlu dibandingkan dengan jadwal pengeluaran.',basis:[by('payment').label,by('expense').label],meaning:'Penerimaan tertunda dan catatan biaya belum jelas. Dampaknya pada ketersediaan uang belum dapat ditentukan hanya dari jawaban ini.',action:'Susun daftar uang yang diperkirakan masuk dan pengeluaran jatuh tempo dua minggu ke depan. Periksa apakah waktunya bertemu.'});
if(by('capacity').status==='issue'&&by('promise').status==='issue')connections.push({title:'Kapasitas dan janji penjualan perlu dicocokkan.',basis:[by('capacity').label,by('promise').label],meaning:'Ada kendala sumber daya sekaligus keluhan atas janji. Jangan menaikkan kapasitas sebelum tahu apakah kedua temuan terjadi pada pesanan yang sama.',action:'Ambil satu pesanan bermasalah, lalu bandingkan janji waktu dengan orang, alat, dan stok yang tersedia saat pesanan diterima.'});
if(by('partner').status==='issue'&&['watch','unknown'].includes(by('alternative').status))connections.push({title:'Gangguan mitra belum didukung alternatif yang siap.',basis:[by('partner').label,by('alternative').label],meaning:'Gangguan mitra sudah dilaporkan, sementara penanganan alternatif belum siap atau belum diketahui.',action:'Pilih gangguan mitra yang pernah terjadi dan pastikan satu alternatif dapat memenuhi kebutuhan yang sama.'});
if(by('information').status==='issue'&&['watch','unknown'].includes(by('standard').status))connections.push({title:'Informasi yang sulit ditemukan dan standar kerja perlu ditata bersama.',basis:[by('information').label,by('standard').label],meaning:'Gangguan akses informasi dan standar yang belum jelas sama-sama muncul. Perlu diperiksa apakah keduanya menghambat pekerjaan yang sama.',action:'Pilih satu pekerjaan terhambat, lalu tempatkan instruksi dan informasi yang dibutuhkan dalam satu lokasi yang dapat diakses.'});
if(['watch','unknown'].includes(by('pricing').status)&&by('margin').status==='issue')connections.push({title:'Dasar harga perlu diperiksa bersama biaya langsung.',basis:[by('pricing').label,by('margin').label],meaning:'Anda melaporkan transaksi yang belum menutup biaya langsung, sementara dasar harga belum jelas. Belum cukup untuk memutuskan menaikkan harga sebelum komponennya diperiksa.',action:'Bandingkan harga diterima, potongan, dan biaya langsung pada produk yang sama sebelum memilih perubahan.'});
if(by('delivery').status==='issue'&&by('partner').status==='issue')connections.push({title:'Gangguan penyerahan perlu dicocokkan dengan kinerja mitra.',basis:[by('delivery').label,by('partner').label],meaning:'Kedua gangguan dilaporkan. Catatan pesanan diperlukan untuk melihat apakah masalah mitra terjadi pada penyerahan yang sama.',action:'Cocokkan satu pesanan yang terlambat atau kurang dengan catatan pengerjaan mitra dan waktu serah terimanya.'});
const inconsistencies=[];
const partnerFindings=findings.filter(f=>f.blockId==='partners');if(partnerFindings.some(f=>f.status==='na')&&partnerFindings.some(f=>f.status==='issue'))inconsistencies.push('Jawaban tentang mitra menyebut tidak ada ketergantungan kritis, sekaligus ada gangguan mitra. Periksa apakah jawaban membahas mitra atau periode yang sama.');
areas.forEach(a=>{a.counts=Object.fromEntries(Object.keys(labels).map(s=>[s,a.findings.filter(f=>f.status===s).length]));a.lead=[...a.findings].sort((x,y)=>order[x.status]-order[y.status])[0];const active=a.findings.filter(f=>['issue','watch'].includes(f.status));a.summary=active.length?active.slice(0,2).map(f=>f.title).join(' ')+(a.counts.good?' Di sisi lain, '+a.counts.good+' jawaban menunjukkan praktik pendukung sudah tersedia.':'')+(a.counts.unknown?' Masih ada '+a.counts.unknown+' hal yang belum diketahui.':''):a.counts.unknown?'Informasi pada '+a.counts.unknown+' dari empat pertanyaan belum cukup. Lengkapi bukti sebelum menyimpulkan kondisi area ini.':a.counts.na===4?'Anda menyatakan area ini belum relevan bagi model bisnis saat ini. Tidak dianggap sebagai kelemahan.':'Jawaban menunjukkan praktik pendukung pada area ini tersedia. Tetap periksa pelaksanaannya melalui catatan nyata.';});
if(by('payment').status==='issue'&&['watch','unknown'].includes(by('sales').status))areas.find(a=>a.id==='revenue').summary='Pembayaran terlambat dilaporkan, sementara penerimaan belum terpisah dengan jelas dari penjualan. Catatan penjualan belum cukup untuk menentukan tagihan yang perlu ditindaklanjuti. Mulai dengan daftar tagihan, jumlah tersisa, dan jatuh temponya.';
if(by('rework').status==='issue'&&['watch','unknown'].includes(by('standard').status))areas.find(a=>a.id==='activities').summary='Kesalahan yang sama berulang, sementara standar kerja belum konsisten atau belum diketahui. Periksa satu pekerjaan berulang, tetapkan kriteria hasil, lalu amati apakah kesalahan masih terjadi. Hubungan sebab-akibatnya belum terbukti.';
const topAreas=[...areas].filter(a=>a.status!=='na').sort((a,b)=>order[a.status]-order[b.status]||b.counts.issue-a.counts.issue).slice(0,3);
const context=[];
if(profile.teamSize==='solo')context.push('Anda menjalankan bisnis sendiri. Mulai dengan satu checklist dan satu tempat penyimpanan informasi; pembagian tugas tim belum menjadi langkah pertama.');
else if(profile.teamSize)context.push('Tim berjumlah '+teams[profile.teamSize]+', termasuk owner. Pilih satu penanggung jawab untuk tindak lanjut; pastikan informasi dan standar dapat diakses orang yang menjalankan pekerjaan.');
if(profile.businessAge==='pre')context.push('Bisnis belum beroperasi. Jawaban tentang transaksi merupakan rencana atau informasi awal, bukan bukti kinerja. Rekomendasi yang membutuhkan transaksi baru digunakan setelah uji penawaran atau transaksi pertama.');
else if(profile.businessAge==='new')context.push('Usaha masih berusia kurang dari satu tahun. Gunakan transaksi yang sudah tersedia; jumlah pengalaman yang sedikit belum cukup untuk menyimpulkan pola jangka panjang.');
const industryNotes={food:'Dalam makanan dan minuman, contoh bukti operasional adalah ketepatan pesanan, bahan yang terpakai, sisa produk, dan waktu penyerahan.',retail:'Dalam perdagangan, cocokkan stok, transaksi, penukaran, dan biaya per barang; omzet sendiri belum menunjukkan hasil usaha.',manufacturing:'Dalam produksi, periksa bahan, waktu proses, hasil yang ditolak, dan pengerjaan ulang pada pekerjaan yang sama.',service:'Dalam jasa, cocokkan ruang lingkup, revisi, waktu pengerjaan, persetujuan hasil, dan tahapan pembayaran.',education:'Dalam pendidikan atau pelatihan, periksa kesesuaian janji belajar, pengalaman peserta, penyampaian materi, dan hasil latihan yang disepakati.',property:'Dalam properti atau konstruksi, gunakan periode sesuai siklus proyek dan pembayaran bertahap; hasil bulanan saja dapat memberi gambaran yang tidak lengkap.',health:'Dalam kesehatan atau kebugaran, gunakan catatan operasional dan pengalaman layanan tanpa memasukkan informasi kesehatan pribadi pelanggan.',beauty:'Dalam perawatan, periksa konsistensi layanan, penggunaan bahan, jadwal, keluhan, serta kunjungan ulang yang relevan.',travel:'Dalam pariwisata atau penginapan, bedakan periode ramai dan sepi saat membandingkan pesanan dan pemakaian kapasitas.',logistics:'Dalam logistik, cocokkan waktu penerimaan, perjalanan, serah terima, kapasitas, dan biaya layanan pada pesanan yang sama.',agriculture:'Dalam pertanian atau peternakan, sesuaikan periode pemeriksaan dengan siklus produksi atau panen, bukan memaksakan transaksi bulanan.',digital:'Dalam produk digital, periksa alur pembelian, akses penggunaan, dukungan pelanggan, biaya layanan, dan perpanjangan jika memakai langganan.',other:'Sesuaikan periode pemeriksaan dengan siklus transaksi utama bisnis Anda.'};
if(industryNotes[profile.industry])context.push(industryNotes[profile.industry]);
const headline=profile.businessAge==='pre'?'Periksa kesiapan sebelum menilai kinerja.':counts.issue?'Ada kendala nyata yang perlu ditangani.':counts.watch?'Rapikan praktik yang belum konsisten.':counts.unknown?'Lengkapi informasi sebelum mengambil keputusan.':'Jaga praktik yang sudah berjalan.';
const narrative=profile.businessAge==='pre'?'Profil menunjukkan bisnis belum beroperasi. Gunakan laporan sebagai daftar kesiapan dan rencana memperoleh bukti, bukan diagnosis kinerja usaha berjalan.':counts.issue?'Ada '+counts.issue+' jawaban yang melaporkan gangguan. Area awal untuk ditinjau: '+topAreas.map(a=>a.name.toLowerCase()).join(', ')+'. Periksa kejadian dan dampaknya sebelum memilih perbaikan.':counts.watch?'Ada '+counts.watch+' jawaban tentang praktik yang belum konsisten. Gunakan satu fokus untuk memperjelas cara kerja, lalu bandingkan hasilnya dengan pengalaman berikutnya.':counts.unknown?'Sebanyak '+counts.unknown+' jawaban belum memiliki informasi yang cukup. Langkah pertama adalah mengumpulkan bukti, bukan langsung mengubah bisnis.':'Praktik pendukung dilaporkan tersedia pada area yang relevan. Ini bukan sertifikasi kesehatan bisnis; pertahankan pemeriksaan dan catat perubahan yang terjadi.';
return {findings,counts,priorities,areas,connections:connections.slice(0,3),connectionCount:connections.length,inconsistencies,topAreas,context,headline,narrative};
}
root.BC={blocks,questions,labels,industries,teams,ages,WA,analyze};if(typeof module!=='undefined')module.exports=root.BC;
})(typeof window!=='undefined'?window:globalThis);
